/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Business_Logic.*;
/**
 *
 * @author Tamas
 */
public class AccountView extends javax.swing.JFrame {

    //Constructor
    public AccountView() {
        initComponents();
    }
    
    //The custome whose account will be viewed.
    private Customer selectedCustomer;
    public void setSelectedCustomer(Customer customer)
    {
        selectedCustomer = customer;
        lblCustomerName.setText(selectedCustomer.getName() + "'s Account");
    }
    
    //Sets the specified tab to show when AccountView is first displayed.
    public void setStartTab(int tab)
    {
        switch (tab)
        {
            case 0: tabContainer.setSelectedComponent(tabFindCar);
                break;
            case 1: tabContainer.setSelectedComponent(tabRentedCars);
                break;
            case 2: tabContainer.setSelectedComponent(tabReturnedCars);
                break;                    
        }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerName = new javax.swing.JLabel();
        tabContainer = new javax.swing.JTabbedPane();
        tabFindCar = new javax.swing.JTabbedPane();
        tabRentedCars = new javax.swing.JTabbedPane();
        tabReturnedCars = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCustomerName.setText("Customer's Account");

        tabContainer.addTab("Find Car", tabFindCar);
        tabContainer.addTab("Rented Cars", tabRentedCars);
        tabContainer.addTab("Returned Cars", tabReturnedCars);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerName))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCustomerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JTabbedPane tabContainer;
    private javax.swing.JTabbedPane tabFindCar;
    private javax.swing.JTabbedPane tabRentedCars;
    private javax.swing.JTabbedPane tabReturnedCars;
    // End of variables declaration//GEN-END:variables
}
